# fly.toml app configuration file for domo-tryout-app backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "domo-tryout-app"
primary_region = "ams"

[build]
  dockerfile = "../Dockerfile"

[http_service]
  # the port on which your app receives requests over the private network
  internal_port = 9870
  # must be false - Flycast is http-only
  force_https = false
  # Fly Proxy stops Machines based on traffic
  auto_stop_machines = "stop"
  # Fly Proxy starts Machines based on traffic
  auto_start_machines = true
  # Number of Machines to keep running in primary region
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    # Fly Proxy uses this limit to determine Machine excess capacity
    soft_limit = 250

[[vm]]
  memory_mb = 256
  cpu_kind = "shared"
  cpus = 1

